apiVersion: "profile.example.com/v1alpha1"
kind: CurriculumVitae
metadata:
  name: my-new-cv-2
spec:
  name:
    firstName: Johnny
    middleName: Maxxxx
    lastName: Doe
  contactInfo:
    postalCode: "10000"
    street: some Street
    country: New Zealand
    email: "john@gmail.com"
    phoneNumber: "0123456789"
