---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - profile.example.com
  resources:
  - curriculumvitaes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - profile.example.com
  resources:
  - curriculumvitaes/finalizers
  verbs:
  - update
- apiGroups:
  - profile.example.com
  resources:
  - curriculumvitaes/status
  verbs:
  - get
  - patch
  - update
